### ISSUE TITLE
timed out

### ISSUE THREAD

**Issue by DanielOberlechner** [DD2XAlpha/PC_FBIServer#1]
Hi,
I get the message "timed out".

Any idea how to fix that?
Using Win10 and on the DS the newest version of FBI.

Greets from Italy
and thanks in advance! :)

**Comment by DanielOberlechner** [comment]
Ciao,
I've switched now to ftpd for Nitendo DS and that software works just fine ...

I have no idea why FBI isn't working ...

**Comment by Gaboros** [comment]
Same here!

**Comment by DD2XAlpha** [comment]
This problem is normally due to FBI app on the 3DS, other problem could be the wi-fi connection you are using, please do not use hotspots to transfer your games, always use the router. Also try to be close to the router. Sorry for not being able to answer quickly, I've been really busy since the start of 2019.
